# Generated by Django 5.1.7 on 2025-03-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(help_text='Employee ID', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField(max_length=100)),
                ('mtype', models.CharField(max_length=100)),
                ('mlength', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
